<?php

return [
    'street'=>[
        'name'=>'后台',
        'icon'=>'icon iconfont icon-pinpaishang',
        'son'=>[
            'main'=>[
                'name'=>'后台主页',
                'url'=>'main'
            ],
        ]
    ],
    'customer'=>[
        'name'=>'客户管理',
        'icon'=>'icon-direction',
        'son'=>[
            'main'=>[
                'name'=>'客户录入',
                'url'=>'main'
            ],
        ]
    ],
    'daily'=>[
        'name'=>'日报',
        'icon'=>'icon-bag',
        'son'=>[
            'main'=>[
                'name'=>'日报下载',
                'url'=>'main'
            ],
        ]
    ],
    'project'=>[
        'name'=>'项目管理',
        'icon'=>'icon-direction',
        'son'=>[
            'main'=>[
                'name'=>'项目录入',
                'url'=>'main'
            ],
        ]
    ],
    'calendar'=>[
        'name'=>'日历',
        'icon'=>'icon-drawer',
        'son'=>[
            'main'=>[
                'name'=>'备忘录',
                'url'=>'main'
            ],
        ]
    ],
    'finance'=>[
        'name'=>'财务管理',
        'icon'=>'icon iconfont icon-zhanghu',
        'son'=>[
            'main'=>[
                'name'=>'财务管理',
                'url'=>'main'
            ],
        ]
    ],
    'user'=>[
        'name'=>'账户管理',
        'icon'=>'icon-users',
        'son'=>[
            'main'=>[
                'name'=>'账户管理',
                'url'=>'main'
            ],
        ]
    ],
    'leave'=>[
        'name'=>'打卡',
        'icon'=>'icon-users',
        'son'=>[
            'main'=>[
                'name'=>'请假',
                'url'=>'main'
            ],
        ]
    ],
    'notice'=>[
        'name'=>'通知',
        'icon'=>'icon-bubble',
        'son'=>[
            'main'=>[
                'name'=>'通知',
                'url'=>'main'
            ],
        ]
    ],

];
