<?php

return [
    'street'=>[
        'name'=>'后台',
        'icon'=>'icon iconfont icon-pinpaishang',
        'son'=>[
            'main'=>[
                'name'=>'后台主页',
                'url'=>'main'
            ],
        ]
    ],
    'customer'=>[
        'name'=>'客户管理',
        'icon'=>'icon-direction',
        'son'=>[
            'main'=>[
                'name'=>'客户管理',
                'url'=>'main'
            ],
        ]
    ],
    'project'=>[
        'name'=>'项目管理',
        'icon'=>'icon-direction',
        'son'=>[
            'main'=>[
                'name'=>'项目管理',
                'url'=>'main'
            ],
            'list'=>[
                'name'=>'全部项目',
                'url'=>'list'
            ],
        ]
    ],
    'daily'=>[
        'name'=>'日报',
        'icon'=>'icon-bag',
        'son'=>[
            'main'=>[
                'name'=>'全部日报',
                'url'=>'main'
            ],
        ]
    ],
    'calendar'=>[
        'name'=>'日历',
        'icon'=>'icon-drawer',
        'son'=>[
            'main'=>[
                'name'=>'备忘录',
                'url'=>'main'
            ],
            'eventlist'=>[
                'name'=>'全部备忘录',
                'url'=>'eventlist'
            ],
        ]
    ],
    'finance'=>[
        'name'=>'财务管理',
        'icon'=>'icon iconfont icon-zhanghu',
        'son'=>[
            'main'=>[
                'name'=>'销售利润',
                'url'=>'main'
            ],
        ]
    ],
    'user'=>[
        'name'=>'账户管理',
        'icon'=>'icon-users',
        'son'=>[
            'main'=>[
                'name'=>'账户管理',
                'url'=>'main'
            ],
        ]
    ],
    'leave'=>[
        'name'=>'请假和外出',
        'icon'=>'icon-users',
        'son'=>[
            'main'=>[
                'name'=>'申请列表',
                'url'=>'main'
            ],
            'mainlist'=>[
                'name'=>'全部列表',
                'url'=>'mainlist'
            ],
        ]
    ],
    'notice'=>[
        'name'=>'通知',
        'icon'=>'icon-bubble',
        'son'=>[
            'main'=>[
                'name'=>'进行中的通知',
                'url'=>'main'
            ],
            'mainlist'=>[
                'name'=>'全部通知',
                'url'=>'mainlist'
            ],
        ]
    ],

];
